# Metasearch config file. Anywhere in this file, you can reference environment
# variables using placeholders such as ${FOOBAR} that Metasearch will expand at
# runtime.

# An "engine" is an individual content source, e.g. Confluence. All supported
# engines are listed below. You should customize the config values (required
# unless stated otherwise) for all engines that you plan to use and simply
# delete the entries for any engines that you don't plan to use.
engines:
  # Confluence pages
  confluence:
    # Confluence server URL origin
    origin: https://example.atlassian.net
    # Atlassian API token
    token: 8NTHnTHE94xt6E6l6ig5fUbN
    # Atlassian user who owns the API token
    user: admin@example.com

  # Dropbox files and folders
  dropbox:
    # Case-insensitive top-level folder to search in (optional, defaults to all
    # folders)
    folder: untitled (2)
    # Dropbox API token
    token: vqTsOkuz0bAE_znMjyUfeHLkXUa6gj5mG5BS4pjS2pem9tMahbXpS0Hd725GY-oJ

  # Figma files, projects, and teams
  figma:
    # Organization ID, the number that appears in the URL when viewing your
    # Figma organization's home page: https://www.figma.com/files/<org_id>
    organization: 735245445471726247
    # Value of the `figma.st` cookie that gets attached to HTTP requests that
    # your browser makes while logged into the Figma website. If you're not sure
    # how to view this cookie:
    # https://www.dev2qa.com/how-to-view-http-headers-cookies-in-google-chrome-firefox-internet-explorer/
    token: 729509569287108002-eb910a13a599573c8f2ae86ae850ea3f5cb2a1c6de4468d5f566f3e606893e12-1591815511

  # GitHub repo names and descriptions (for GitHub code, use Hound engine)
  github:
    # GitHub organization
    organization: example
    # GitHub personal access token
    token: b701f041284869e7ff1d5b71e65d27119c869aba

  # Hound-indexed code: https://github.com/hound-search/hound
  hound:
    # GitHub organization
    organization: example
    # Hound server URL origin
    origin: https://hound.example.com

  # Jenkins job names
  jenkins:
    # Jenkins server URL origin
    origin: https://jenkins.example.com

  # Jira issue titles and descriptions
  jira:
    # Jira server URL origin
    origin: https://example.atlassian.net
    # Atlassian API token
    token: 8NTHnTHE94xt6E6l6ig5fUbN
    # Atlassian user who owns the API token
    user: admin@example.com

  # Zoom room names
  zoom:
    # Zoom API key used for JWT authentication
    key: iLGl0DWeD4xeWeQWzGi4Ju
    # Zoom API secret used for JWT authentication
    secret: KbJ9Axxi9Md5BfeeGBuXaAofkRlqQoQ3Eff1
